version: '3'

services:
  emqx1:
    image:  emqx/emqx:4.2-rc.2
    container_name: emqx1
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
      - "EMQX_ZONE__EXTERNAL__RETRY_INTERVAL=2s"
      - "EMQX_MQTT__MAX_TOPIC_ALIAS=10"
    ports:
      - 18083:18083
      - 8083:8083/tcp
      - 5683:5683/udp
    volumes:
      - ./emqx/data/emqx-extension-java-sdk-1.0.0.jar:/opt/emqx/data/extension/emqx-extension-java-sdk-1.0.0.jar
      - ./emqx/data/SampleHandler.class:/opt/emqx/data/extension/SampleHandler.class
      - ./emqx/etc/plugins/emqx_extension_hook.conf:/opt/emqx/etc/plugins/emqx_extension_hook.conf
      - ./emqx/etc/emqx.lic:/opt/emqx/etc/emqx.lic
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
  

  emqx2:
    image:  emqx/emqx:4.2-rc.2
    container_name: emqx2
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node2.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
      - "EMQX_ZONE__EXTERNAL__RETRY_INTERVAL=2s"
      - "EMQX_MQTT__MAX_TOPIC_ALIAS=10"
    ports:
      - 18084:18083
      - 8084:8083/tcp
      - 5684:5683/udp
    volumes:
      - ./emqx/data/emqx-extension-java-sdk-1.0.0.jar:/opt/emqx/data/extension/emqx-extension-java-sdk-1.0.0.jar
      - ./emqx/data/SampleHandler.class:/opt/emqx/data/extension/SampleHandler.class
      - ./emqx/etc/plugins/emqx_extension_hook.conf:/opt/emqx/etc/plugins/emqx_extension_hook.conf
      - ./emqx/etc/emqx.lic:/opt/emqx/etc/emqx.lic
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io

  client:
    image: python:3.7.2-alpine3.9
    depends_on:
      - emqx1
      - emqx2
    tty: true
    networks:
        emqx-bridge:

networks:
  emqx-bridge:
    driver: bridge